import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { ConvexClientProvider } from "@/components/Providers/ConvexProvider";
import {Toaster} from "sonner"

const poppins = Poppins({
  weight: ["400", "500", "600", "700"], // Specify the weights you need
  subsets: ["latin"], // Specify the subsets you need
});

export const metadata: Metadata = {
  title: "Content.ai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  suppressHydrationWarning>
      <body className={poppins.className}>
          <ConvexClientProvider>
              <Toaster position={"bottom-center"} />
              {children}
          </ConvexClientProvider>
      </body>
    </html>
  );
}
